package net.dakotapride.desolatum.registry;

import net.dakotapride.desolatum.Desolatum;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class DesolatumCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Desolatum.ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> DESOLATUM_TAB = CREATIVE_MODE_TABS.register("desolatum",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(Blocks.CRYING_OBSIDIAN.asItem()))
                    .title(Component.translatable("itemGroup.desolatum"))
                    .displayItems((displayContext, entries) -> {
                        entries.accept(DesolatumBlocks.PURPURA);
                        entries.accept(DesolatumBlocks.PURPURA_STAIRS);
                        entries.accept(DesolatumBlocks.PURPURA_SLAB);
                        entries.accept(DesolatumBlocks.PURPURA_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_PURPUR_BLOCK);
                        entries.accept(DesolatumBlocks.POLISHED_PURPUR_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_PURPUR_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_PURPUR_WALL);
                        entries.accept(Blocks.PURPUR_BLOCK);
                        entries.accept(Blocks.PURPUR_STAIRS);
                        entries.accept(Blocks.PURPUR_SLAB);
                        entries.accept(DesolatumBlocks.PURPUR_WALL);
                        entries.accept(Blocks.PURPUR_PILLAR);
                        entries.accept(DesolatumBlocks.CHISELED_PURPUR_BLOCK);
                        entries.accept(Blocks.END_ROD);
                        entries.accept(DesolatumBlocks.SHORT_INFIRMUM_WEEDS);
                        entries.accept(DesolatumBlocks.TALL_INFIRMUM_WEEDS);
                        entries.accept(DesolatumBlocks.OBSIDIAN_SPIKE);
                        entries.accept(DesolatumBlocks.OBSIDISED_END_STONE);
                        entries.accept(Blocks.OBSIDIAN);
                        entries.accept(DesolatumBlocks.OBSIDIAN_STAIRS);
                        entries.accept(DesolatumBlocks.OBSIDIAN_SLAB);
                        entries.accept(DesolatumBlocks.OBSIDIAN_WALL);
                        entries.accept(DesolatumBlocks.OBSIDIAN_BRICKS);
                        entries.accept(DesolatumBlocks.OBSIDIAN_BRICK_STAIRS);
                        entries.accept(DesolatumBlocks.OBSIDIAN_BRICK_SLAB);
                        entries.accept(DesolatumBlocks.OBSIDIAN_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_OBSIDIAN);
                        entries.accept(DesolatumBlocks.POLISHED_OBSIDIAN_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_OBSIDIAN_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_OBSIDIAN_WALL);
                        entries.accept(Blocks.CRYING_OBSIDIAN);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_STAIRS);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_SLAB);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_WALL);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_BRICKS);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_BRICK_STAIRS);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_BRICK_SLAB);
                        entries.accept(DesolatumBlocks.CHARGED_OBSIDIAN_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_CHARGED_OBSIDIAN);
                        entries.accept(DesolatumBlocks.POLISHED_CHARGED_OBSIDIAN_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_CHARGED_OBSIDIAN_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_CHARGED_OBSIDIAN_WALL);
                        entries.accept(DesolatumBlocks.VILIDALLUM_BLOCK);
                        entries.accept(DesolatumItems.VILIDALLUM_SHARD);
                        entries.accept(Blocks.END_STONE);
                        entries.accept(DesolatumBlocks.END_STONE_STAIRS);
                        entries.accept(DesolatumBlocks.END_STONE_SLAB);
                        entries.accept(DesolatumBlocks.END_STONE_WALL);
                        entries.accept(Blocks.END_STONE_BRICKS);
                        entries.accept(Blocks.END_STONE_BRICK_STAIRS);
                        entries.accept(Blocks.END_STONE_BRICK_SLAB);
                        entries.accept(Blocks.END_STONE_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_END_STONE);
                        entries.accept(DesolatumBlocks.POLISHED_END_STONE_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_END_STONE_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_END_STONE_WALL);
                        entries.accept(DesolatumBlocks.CHISELED_END_STONE);
                        entries.accept(DesolatumBlocks.DUSTY_END_STONE);
                        entries.accept(DesolatumBlocks.RICH_DUSTY_END_STONE);
                        entries.accept(DesolatumBlocks.DEAD_CHORUS_PLANT);
                        entries.accept(DesolatumBlocks.TRISTIS_SLUDGE);
                        entries.accept(Blocks.END_PORTAL_FRAME);
                        entries.accept(Items.ENDER_CHEST);
                        entries.accept(Items.ENDER_PEARL);
                        entries.accept(Items.ENDER_EYE);
                        entries.accept(Items.END_CRYSTAL);
                        entries.accept(DesolatumBlocks.CHLORITE);
                        entries.accept(DesolatumBlocks.CHLORITE_STAIRS);
                        entries.accept(DesolatumBlocks.CHLORITE_SLAB);
                        entries.accept(DesolatumBlocks.CHLORITE_WALL);
                        entries.accept(DesolatumBlocks.CHLORITE_BRICKS);
                        entries.accept(DesolatumBlocks.CHLORITE_BRICK_STAIRS);
                        entries.accept(DesolatumBlocks.CHLORITE_BRICK_SLAB);
                        entries.accept(DesolatumBlocks.CHLORITE_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_CHLORITE);
                        entries.accept(DesolatumBlocks.POLISHED_CHLORITE_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_CHLORITE_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_CHLORITE_WALL);
                        entries.accept(DesolatumBlocks.CHISELED_CHLORITE);
                        entries.accept(DesolatumBlocks.MUDROCK);
                        entries.accept(DesolatumBlocks.MUDROCK_STAIRS);
                        entries.accept(DesolatumBlocks.MUDROCK_SLAB);
                        entries.accept(DesolatumBlocks.MUDROCK_WALL);
                        entries.accept(DesolatumBlocks.MUDROCK_BRICKS);
                        entries.accept(DesolatumBlocks.MUDROCK_BRICK_STAIRS);
                        entries.accept(DesolatumBlocks.MUDROCK_BRICK_SLAB);
                        entries.accept(DesolatumBlocks.MUDROCK_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_MUDROCK);
                        entries.accept(DesolatumBlocks.POLISHED_MUDROCK_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_MUDROCK_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_MUDROCK_WALL);
                        entries.accept(DesolatumBlocks.CHISELED_MUDROCK);
                        entries.accept(DesolatumBlocks.PETALITE);
                        entries.accept(DesolatumBlocks.PETALITE_STAIRS);
                        entries.accept(DesolatumBlocks.PETALITE_SLAB);
                        entries.accept(DesolatumBlocks.PETALITE_WALL);
                        entries.accept(DesolatumBlocks.PETALITE_BRICKS);
                        entries.accept(DesolatumBlocks.PETALITE_BRICK_STAIRS);
                        entries.accept(DesolatumBlocks.PETALITE_BRICK_SLAB);
                        entries.accept(DesolatumBlocks.PETALITE_BRICK_WALL);
                        entries.accept(DesolatumBlocks.POLISHED_PETALITE);
                        entries.accept(DesolatumBlocks.POLISHED_PETALITE_STAIRS);
                        entries.accept(DesolatumBlocks.POLISHED_PETALITE_SLAB);
                        entries.accept(DesolatumBlocks.POLISHED_PETALITE_WALL);
                        entries.accept(DesolatumBlocks.CHISELED_PETALITE);
                        entries.accept(DesolatumBlocks.VIRIDITE_BLOCK);
                        entries.accept(DesolatumItems.VIRIDITE_SHARD);
                        entries.accept(DesolatumItems.DECREPIT_STICK);
                    }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
